### ISSUE TITLE
Рандомая длина пароля и справка

### ISSUE THREAD

**Issue by prophetl33t** [trpo2021/cw-ip-014_password-generator#8]
Добавить параметры:
--passRndLen
Вывод справки если юзер не ввел аргументы
Описания параметров см. https://github.com/trpo2021/cw-ip-014_password-generator/wiki

**Comment by 1HGGD1** [comment]
Закончил выполнение задачи 18cc8d932f02c9819d4a4da26dde8af6e668d61c
